// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertController from "./alert_controller"
import LikesController from "./likes_controller"
import TextareaAutoResizeController from "./textarea_auto_resize_controller"

application.register("alert", AlertController);
application.register("textarea-auto-resize", TextareaAutoResizeController);
application.register("likes", LikesController);
