// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertController from "./alert_controller"
import LikesController from "./likes_controller"
import TextareaAutoResizeController from "./textarea_auto_resize_controller"
import TurboFrameController from "./turbo_frame_controller"
import ReadMore from './read_more_controller'
import LazyLoader from './lazy_loader'

application.register("alert", AlertController);
application.register("textarea-auto-resize", TextareaAutoResizeController);
application.register("likes", LikesController);
application.register('turbo-frame', TurboFrameController);
application.register('lazy-loader', LazyLoader);
application.register('read-more', ReadMore);